language: generic
services:
  - docker
env:
  global:
    - DOCKERBUILDER=greenaddress/core_builder_for_android
    - DOCKERHASH=d10ad6bea2a91ae11c774063c8c3c4e02582c0d8080c7065b2685242a3f2f44d
    - REPO=https://github.com/bitcoin/bitcoin.git
    - COMMIT=00ffe5aca134f424351b05a85da4eef9c3e4553a
    - TARGETHOST=aarch64-linux-android
    - BITS=64
    - REPONAME=bitcoin
    - RENAME=bitcoin
    - CONFIGURE=--disable-man
  matrix:
    - unused=true
    - TARGETHOST=armv7a-linux-androideabi BITS=32
    - TARGETHOST=x86_64-linux-android
    - TARGETHOST=i686-linux-android BITS=32
    - REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - TARGETHOST=armv7a-linux-androideabi BITS=32 REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - TARGETHOST=x86_64-linux-android REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - TARGETHOST=i686-linux-android BITS=32 REPO=https://github.com/bitcoinknots/bitcoin.git COMMIT=5e1c2d13f506e58513064ecbd914e00a944ee6a0
    - REPO=https://github.com/elementsproject/elements.git COMMIT=da7b8abda6f7cbe2ca1c8b7a038a969147e1c9cb REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=armv7a-linux-androideabi BITS=32 REPO=https://github.com/elementsproject/elements.git COMMIT=da7b8abda6f7cbe2ca1c8b7a038a969147e1c9cb REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=x86_64-linux-android REPO=https://github.com/elementsproject/elements.git COMMIT=da7b8abda6f7cbe2ca1c8b7a038a969147e1c9cb REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid
    - TARGETHOST=i686-linux-android BITS=32 REPO=https://github.com/elementsproject/elements.git COMMIT=da7b8abda6f7cbe2ca1c8b7a038a969147e1c9cb REPONAME=elements RENAME=liquid CONFIGURE=--enable-liquid

script:
  - docker run -v $PWD:/repo $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "/repo/fetchbuild.sh $REPO $COMMIT $REPONAME $RENAME $CONFIGURE $TARGETHOST $BITS"
